<?php

namespace BDE\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * commentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentaireRepository extends EntityRepository
{
}
