<?php

namespace BDE\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * jaimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class jaimeRepository extends EntityRepository
{
}
