bde_site_homepage:
    path:     /
    defaults: { _controller: BDESiteBundle:Accueil:index }

bde_site_login:
    path:     /login
    defaults: { _controller: BDESiteBundle:login }

bde_site_register:
    path:     /register
    defaults: { _controller: BDESiteBundle:register }

bde_site_layout:
    path:     /layout
    defaults: { _controller: BDESiteBundle:Layout:index }

bde_site_layout_add:
    path:     /layout/add
    defaults: { _controller: BDESiteBundle:Layout:add }

bde_site_layout_del:
    path:     /del/{id}
    defaults: { _controller: BDESiteBundle:Layout:del }

bde_site_layout_delete:
    path:     /layout/del/{id}
    defaults: { _controller: BDESiteBundle:Layout:del }

bde_site_layout_activiteproposer:
    path:     /layout/activite
    defaults: { _controller: BDESiteBundle:Layout:activiteproposer }

bde_site_layout_activite:
    path:     /layout/activite/{id}
    defaults: { _controller: BDESiteBundle:Layout:activite }

bde_site_gestion_user:
    path:     /gestion
    defaults: { _controller: BDESiteBundle:gestion:users}

bde_site_gestion_boutique:
    path:     /layout/boutique
    defaults: { _controller: BDESiteBundle:Layout:boutique}

bde_site_MLegales:
    path:     /MentionsLegales
    defaut:   {_controler: BDESiteBundle:MentionsLegales}








