bde_site_homepage:
    path:     /
    defaults: { _controller: BDESiteBundle:Accueil:index }

bde_site_login:
    path:     /login
    defaults: { _controller: BDESiteBundle:Accueil:login }

bde_site_register:
    path:     /register
    defaults: { _controller: BDESiteBundle:Accueil:register }

bde_site_layout:
    path:     /layout
    defaults: { _controller: BDESiteBundle:Layout:index }

bde_site_layout_add:
    path:     /layout/add
    defaults: { _controller: BDESiteBundle:Layout:add }

bde_site_layout_del:
    path:     /layout/del/{id}
    defaults: { _controller: BDESiteBundle:Layout:del }


bde_site_layout_activite:
    path:     /layout/activite/{id}
    defaults: { _controller: BDESiteBundle:Layout:activite }

