bde_site_homepage:
    path:     /
    defaults: { _controller: BDESiteBundle:Accueil:index }

bde_site_login:
    path:     /login
    defaults: { _controller: BDESiteBundle:Accueil:login }

bde_site_register:
    path:     /register
    defaults: { _controller: BDESiteBundle:Accueil:register }

bde_site_layout:
    path:     /layout
    defaults: { _controller: BDESiteBundle:Layout:index }