bde_site_homepage:
    path:     /
    defaults: { _controller: BDESiteBundle:Accueil:index }

bde_site_login:
    path:     bde_site_login
    defaults: { _controller: BDESiteBundle:Accueil:login }

bde_site_register:
    path:     bde_site_register
    defaults: { _controller: BDESiteBundle:Accueil:register }

bde_site_layout:
    path:     bde_site_layout
    defaults: { _controller: BDESiteBundle:Layout:index }

bde_site_layout_add:
    path:     bde_site_layout_add
    defaults: { _controller: BDESiteBundle:Layout:add }

bde_site_layout_del:
    path:     bde_site_layout_del_{id}
    defaults: { _controller: BDESiteBundle:Layout:del }


bde_site_layout_activite:
    path:     bde_site_layout_activite_{id}
    defaults: { _controller: BDESiteBundle:Layout:activite }

bde_site_gestion_user:
    path:     bde_site_gestion_user
    defaults: { _controller: BDESiteBundle:gestion:users }






